services:
  nextjs-app1:
    container_name: nextjs-app1
    build:
      context: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs-app2:
    container_name: nextjs-app2
    build:
      context: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app1
      - nextjs-app2
    restart: always
    networks:
      - webnet

networks:
  webnet:
