- name: Create swap file
  command: fallocate -l 2G /swapfile
  args:
    creates: /swapfile

- name: Set permissions
  file:
    path: /swapfile
    mode: '0600'

- name: Setup swap
  command: mkswap /swapfile

- name: Enable swap
  command: swapon /swapfile

- name: Persist swap
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'
